# ---------------------------------------------------------------------------
# Pre-render step: write one page per paper under papers/<slug>/index.qmd
# from the Papers tab of the CV spreadsheet.
#
# Wired into _quarto.yml as `pre-render`, so `quarto render` always rebuilds
# these from the sheet. The generated directory is gitignored — it is output,
# not source. Edit the sheet, or paper_utils.R, not the generated files.
# ---------------------------------------------------------------------------

source("helpers.R")
source("paper_utils.R")

out_dir <- "papers"
cache_dir <- dirname(PU_CACHE)

# Fetch the whole spreadsheet, once per compile. This happens BEFORE anything
# is deleted, so a failed fetch aborts the render with the previous pages still
# on disk rather than wiping them.
message("generate_papers.R: fetching the CV spreadsheet ...")
sheets <- get_cv_data()
all_sheets <- sheets(NULL)
papers <- sheets("Papers")
p <- pu_prepare(papers)

# every page reads the snapshot instead of hitting the sheet again
dir.create(cache_dir, showWarnings = FALSE, recursive = TRUE)
saveRDS(all_sheets, PU_CACHE)
message(
    "generate_papers.R: fetched ", length(all_sheets), " sheets (",
    paste(names(all_sheets), collapse = ", "), "); ",
    nrow(papers), " papers"
)

# start from a clean slate so renamed or removed papers do not linger
if (dir.exists(out_dir)) unlink(out_dir, recursive = TRUE)
dir.create(out_dir, showWarnings = FALSE)

yaml_str <- function(x) paste0('"', gsub('"', '\\\\"', x), '"')

# a plain-text, single-line summary for <meta name="description">
meta_desc <- function(abstract, venue) {
    txt <- if (nzchar(abstract)) abstract else venue
    txt <- gsub("[\r\n]+", " ", txt)
    txt <- gsub("[[:space:]]+", " ", trimws(txt))
    if (nchar(txt) > 200) paste0(substr(txt, 1, 197), "...") else txt
}

for (i in seq_len(p$n)) {
    if (!nzchar(p$slug[i])) next

    dir.create(file.path(out_dir, p$slug[i]), recursive = TRUE, showWarnings = FALSE)

    abstract_html <- if (nzchar(p$abstract[i])) {
        paste0(
            '<section class="paper-abstract">',
            pu_paragraphs(p$abstract[i]),
            "</section>"
        )
    } else {
        ""
    }

    body <- paste0(
        '<article class="paper">',
        '<h1 class="paper-title">', pu_esc(p$title[i]), "</h1>",
        '<p class="paper-authors">', p$authors_html[i], "</p>",
        ifelse(nzchar(p$venue_line[i]),
            paste0('<p class="paper-venue">', p$venue_line[i], "</p>"), ""),
        ifelse(nzchar(p$cat_html[i]) || nzchar(p$award_html[i]),
            paste0('<div class="pub-meta">', p$cat_html[i], p$award_html[i], "</div>"), ""),
        abstract_html,
        '<div class="pub-links paper-links">', p$links[i], p$cite_btn[i], "</div>",
        p$cite_box[i],
        "</article>",
        pu_cite_script()
    )

    lines <- c(
        "---",
        paste0("title: ", yaml_str(p$title[i])),
        paste0("pagetitle: ", yaml_str(paste0(p$title[i], " - Patrik Kenfack"))),
        paste0("description: ", yaml_str(meta_desc(p$abstract[i], p$venue[i]))),
        "page-layout: full",
        "toc: false",
        "comments: false",
        "---",
        "",
        "<!-- GENERATED by generate_papers.R from the Papers sheet. Do not edit. -->",
        "",
        "```{=html}",
        "<style>#title-block-header { display: none; }</style>",
        '<div class="with-aside">',
        '<div class="page-aside" role="complementary">',
        pu_profile_html(),
        "</div>",
        '<div class="page-main">',
        body,
        "</div>",
        "</div>",
        "```",
        ""
    )

    writeLines(lines, file.path(out_dir, p$slug[i], "index.qmd"), useBytes = TRUE)
}

message("generate_papers.R: wrote ", p$n, " paper pages under ", out_dir, "/")
